---
- hosts: vagrant
  sudo: yes
  tasks:
    - name: Update cache
      apt: update_cache=yes
    - name: Install nginx
      apt: pkg=nginx state=present
    - name: Start nginx
      command: sudo service nginx start
    - name: Install emacs
      apt: pkg=emacs state=present
    - name: Install python3-dev
      apt: pkg=python3-dev state=present